export const categories = [
  { value: "react", label: "React" },
  { value: "angular", label: "Angular" },
  { value: "svelte", label: "Svelte" },
  { value: "vue", label: "Vue" },
  { value: "riot", label: "Riot" },
  { value: "next", label: "Next.js" },
  { value: "blitz", label: "Blitz.js" },
  { value: "typescript", label: "Typescript" },
  { value: "mongodb", label: "Mongo DB" },
  { value: "node", label: "Node.js" },
  { value: "web design", label: "Web Design" },
  { value: "flutter", label: "flutter" },
  { value: "react native", label: "React native" },
  { value: "rust", label: "Rust" },
  { value: "python", label: "Python" },
  { value: "julia", label: "Julia" },
  { value: "ruby", label: "Ruby" },
  { value: "carbon", label: "Carbon" },
  { value: "c++", label: "C++" },
  { value: "kubernetes", label: "Kubernetes" },
  { value: "docker", label: "Docker" },
  { value: "three.js", label: "Three.js" },
  { value: "spline", label: "spline" },
  { value: "blockchain", label: "Blockchain" },
  { value: "cryptocurrency", label: "Cryptocurrency" },
  { value: "ethereum", label: "Ethereum" },
  { value: "bitcoin", label: "Bitcoin" },
  { value: "polkadot", label: "Polkadot" },
  { value: "web3", label: "web3" },
  { value: "dao", label: "DAO" },
  { value: "dapps", label: "DAPPS" },
  { value: "cloudinary", label: "Cloudinary" },
  { value: "graphql", label: "GraphQL" },
  { value: "git", label: "Git" },
  { value: "electron.js", label: "Electron.js" },
  { value: "ui/ux", label: "UI/UX" },
  { value: "testing", label: "testing" },
  { value: "framer-motion", label: "framer-motion" },
  { value: "kotlin", label: "kotlin" },
  { value: "jetpack compose", label: "Jetpack Compose" },
  { value: "aws", label: "AWS" },
  { value: "google cloud", label: "Google Cloud" },
  { value: "microsoft azure", label: "Microsoft Azure" },
  { value: "machine learning", label: "Machine Learning" },
  { value: "artificial intelligence", label: "Artificial Intelligence" },
  { value: "ar/vr", label: "AR/VR" },
  { value: "", label: "All" },
];

export const headerLinks = [
  {
    link: "/home",
    label: "Home",
  },
  {
    link: "/about",
    label: "About",
  },
  {
    link: "/featuers",
    label: "Featuers",
  },

  {
    link: "#1",
    label: "More",
    links: [
      {
        link: "/docs",
        label: "Documentation",
      },
      {
        link: "/resources",
        label: "Resources",
      },
      {
        link: "/community",
        label: "Community",
      },
      {
        link: "/blog",
        label: "Blog",
      },
    ],
  },
];
